# Pytorch_数据基础

- Tensor用以表示矩阵（多维数据），类似Numpy和ndarray，不同的是，它可以使用GPU加速
- Variable是神经网络计算图中特有的概念，它提供了自动求导的功能。


In [1]:
import torch

In [2]:
a = torch.Tensor([[1,2],[3,4],[5,6]])

In [3]:
print(a)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


In [4]:
torch.zeros((3,2))

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [5]:
torch.randn((3,2))

tensor([[ 0.0326,  0.4061],
        [-1.0813,  0.5549],
        [ 0.7799, -2.7289]])

In [6]:
a[1,1] = 50

In [7]:
print(a)

tensor([[ 1.,  2.],
        [ 3., 50.],
        [ 5.,  6.]])


In [8]:
b = a.numpy()

In [9]:
b

array([[ 1.,  2.],
       [ 3., 50.],
       [ 5.,  6.]], dtype=float32)

In [10]:
c = torch.from_numpy(b)

In [11]:
if torch.cuda.is_available():
    d = a.cuda()
    print('cuda')

cuda


In [13]:
e = d.cpu()

In [14]:
e

tensor([[ 1.,  2.],
        [ 3., 50.],
        [ 5.,  6.]])

In [15]:
d

tensor([[ 1.,  2.],
        [ 3., 50.],
        [ 5.,  6.]], device='cuda:0')

In [16]:
from torch.autograd import Variable
f = Variable(a, requires_grad=True)

In [17]:
f

tensor([[ 1.,  2.],
        [ 3., 50.],
        [ 5.,  6.]], requires_grad=True)

In [18]:
x = Variable(torch.Tensor([1]), requires_grad=True)
a = Variable(torch.Tensor([2]), requires_grad=True)
b = Variable(torch.Tensor([3]), requires_grad=True)

In [19]:
x,a,b

(tensor([1.], requires_grad=True),
 tensor([2.], requires_grad=True),
 tensor([3.], requires_grad=True))

In [20]:
y = a * x + b

In [21]:
y

tensor([5.], grad_fn=<AddBackward0>)

In [22]:
y.backward()

In [23]:
x.grad

tensor([2.])

In [24]:
b.grad

tensor([1.])

In [25]:
a.grad

tensor([1.])

In [26]:
b.data

tensor([3.])

In [27]:
b

tensor([3.], requires_grad=True)

In [33]:
x = torch.tensor([1.0], requires_grad=True)
a = torch.tensor([2.0], requires_grad=True)
b = torch.tensor([3.0], requires_grad=True)
x, a, b

(tensor([1.], requires_grad=True),
 tensor([2.], requires_grad=True),
 tensor([3.], requires_grad=True))

In [35]:
y = a * x + b
y

tensor([5.], grad_fn=<AddBackward0>)

In [36]:
y.backward()

In [37]:
x.grad, b.grad, a.grad, b.data

(tensor([2.]), tensor([1.]), tensor([1.]), tensor([3.]))

## 常见的数据处理函数

- 增加维度
- 减小维度
- 转换维度
- cat拼接
- stack拼接
- transpose两维度互换
- perumute多维度切换

In [ ]:
torch.squeeze()
torch.unsqueeze

In [38]:
a = torch.tensor([1,2,3])

In [39]:
b = torch.unsqueeze(a, dim=1)

In [40]:
c = torch.squeeze(b, dim=1)

In [41]:
b = torch.unsqueeze(a, dim=0)

In [42]:
e = torch.randn((6))

In [43]:
e

tensor([-1.2222,  1.0281,  0.5613,  1.6022,  0.7385,  1.2336])

In [45]:
f = e.view((2,3))

In [46]:
f = e.view((-1, 3))

In [ ]:
b = torch.unsqueeze(a, dim=1)

In [48]:
x = torch.tensor([[1,2],[3,4]])
y = torch.tensor([[5,6],[7,8]])
x, y

(tensor([[1, 2],
         [3, 4]]), tensor([[5, 6],
         [7, 8]]))

In [50]:
c = torch.cat([x, y], dim=0)

In [63]:
torch.cat([f, x.float()], dim=0)

RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 3 and 2 in dimension 1 at /pytorch/aten/src/TH/generic/THTensorMoreMath.cpp:1333

In [64]:
hhh = torch.stack((x, y), dim=0)

In [65]:
hhh

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

In [67]:
eeee = torch.transpose(f, 1, 0)

In [71]:
ff = torch.randn((10, 30 ,20))

In [72]:
ff.permute()

RuntimeError: Dimension out of range (expected to be in range of [-3, 2], but got 10)